name: leitor_ebooks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  dio: ^5.4.0
  path_provider:
  vocsy_epub_viewer: ^2.0.0
  flutter:
    sdk: flutter
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.vocsy.epub_viewer
        pluginClass: EpubViewerPlugin
      ios:
        pluginClass: EpubViewerPlugin


  assets:
     - assets/epub/